### PR TITLE
Drop support for node versions below 4 

### PR DESCRIPTION
**Pull request by vieiralucas**
This PR also updates the dependencies and adds a `package-lock.json` file

### CODE REVIEW

**Comment by vieiralucas** [comment]
@chaijs/chai-fs Can I get a review here? Thanks ❤️

**Comment by vieiralucas** [comment]
It looks like there is something wrong with `dependency-ci`.
All chai projects are `pending`, @keithamus do you know how to fix this?

**Comment by keithamus** [comment]
@vieiralucas fixed the dependency ci thing. I think we should look at enabling https://github.com/probot/settings across the org to allow for these kinds of settings to be fixed with PRs, so I don't end up blocking on this stuff.

**Comment by keithamus** [comment]
The commit where we drop node 4 should probably be demarkated with a `BREAKING CHANGE` section in the commit message btw.

**Comment by vieiralucas** [comment]
Done

**Comment by vieiralucas** [comment]
Do you think I should make a 2.0 release? Just to make sure that the `major version bump` is done?

**Comment by keithamus** [comment]
Yeah a major release would be good.

**Pull request merged**
