### PR TITLE
v1.0.0 (attempt #2)

### PR DESCRIPTION
**Pull request by BigstickCarpet**
I originally tried to release v1.0.0 in PR #25, but that failed due broken tests.  The tests have been fixed now (PR #27), so let's try this again.

- I updated all dependencies
- I updated `peerDependencies` to support Chai 4.x
- I updated `.travis.yml` to include all major versions of Node in the build matrix
- I moved the `1.0.0` tag from PR #25 to this PR

### CODE REVIEW

**Comment by BigstickCarpet** [comment]
Woot!  [All tests passed!](https://travis-ci.org/chaijs/chai-fs/builds/170773862)  Let's publish this baby!

@meeber @keithamus - Can I get a LGTM?  :)

**Comment by BigstickCarpet** [comment]
btw, this PR also resolves Issue #24, Issue #28, and Issue #21

**Comment by keithamus** [comment]
Ooh new shiny, LGTM!

**Comment by keithamus** [comment]
@BigstickCarpet to release this, you just need to publish [this tag](https://github.com/chaijs/chai-fs/releases/edit/untagged-b928f077e75a128a9ced) - would you also be so kind as to draft some release notes for this release? Thankyou kindly!

**Comment by BigstickCarpet** [comment]
Done and released.  Woot!

**Comment by BigstickCarpet** [comment]
@keithamus - What does it take to get [this page](http://chaijs.com/plugins/chai-fs/) updated?

**Comment by keithamus** [comment]
@BigstickCarpet that automatically gets updated every 24 hours so nothing 😉

**Comment by BigstickCarpet** [comment]
👍  Good to know

**Pull request merged**
