### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by BigstickCarpet**
Bumped the version number in `package.json` and tagged the commit for publish to npm

This fixes https://github.com/chaijs/chai-fs/issues/21, https://github.com/chaijs/chai-fs/issues/23, and https://github.com/chaijs/chai-fs/issues/24

### CODE REVIEW

**Comment by keithamus** [comment]
LGTM 😉 😆 🎉

**Comment by BigstickCarpet** [comment]
LGTM 👍 

(does it let me count myself?)

**Comment by BigstickCarpet** [comment]
guess not.  oh well.  worth a try 😜

**Comment by meeber** [comment]
LGTM

**Comment by keithamus** [comment]
Ahh, it does normally, I think it doesn't count because there's a [typo in the MAINTAINERS file](https://github.com/chaijs/chai-fs/blob/master/MAINTAINERS#L2). @meeber can approve this one, you might want to PR a fix for your username in MAINTAINERS though @BigstickCarpet

**Comment by keithamus** [comment]
Ahh speak of the devil 👿

**Comment by BigstickCarpet** [comment]
@keithamus - I don't see a typo... unless... is it case sensitive?

**Comment by BigstickCarpet** [comment]
@keithamus - Merging the PR didn't kick-off a new [Travis-CI build](https://travis-ci.org/chaijs/chai-fs/builds).  Any clue why not?

**Comment by keithamus** [comment]
@BigstickCarpet no idea why it didn't. I switched the travis build on and off, we'll see if that helps.

**Comment by keithamus** [comment]
Looks like we've got a build going now; https://travis-ci.org/chaijs/chai-fs/builds/166746669

**Comment by BigstickCarpet** [comment]
Build failed :(  I'm looking into it.  Looks like it's just something to do with the ordering of files in a directory

**Pull request merged**
